version: '3.8'

services:
  # Main application
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../:/app
      - /app/node_modules
      - sandbox-data:/app/sandbox-data
    depends_on:
      - sandbox

  # Execution sandbox
  sandbox:
    build:
      context: ../docker/sandbox
      dockerfile: Dockerfile
    volumes:
      - sandbox-data:/manus-sandbox
    environment:
      - MAX_MEMORY=512m
      - CPU_LIMIT=0.5
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    restart: unless-stopped

volumes:
  sandbox-data: